services:

  backend:
    image: challenge-backend-api
    container_name: challenge-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:123@db:5432/challenge_db" # Cambiar la cadena de conexiÃ³n 
    volumes:
      - .:/app
    depends_on:
      - db
      - migrations
    restart: unless-stopped

  migrations:
    build: .
    command: >
      sh -c "sleep 5 && 
             alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL_SYNC=postgresql+psycopg2://admin:123@db:5432/challenge_db
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=challenge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d challenge_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: